name: Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      
      - name: Run tests
        run: go test ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      
      - name: Build
        run: |
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' || 'linux' }}
          GOARCH=amd64
          OUTPUT_NAME="go-blockchain${{ matrix.os == 'windows-latest' && '.exe' || '' }}"
          
          go build -o $OUTPUT_NAME -ldflags="-s -w" ./cmd/main.go
          mkdir release
          mv $OUTPUT_NAME release/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: go-blockchain-${{ matrix.os }}
          path: release/
  
  release:
    name: Create Release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/go-blockchain-ubuntu-latest/*
            artifacts/go-blockchain-windows-latest/*
            artifacts/go-blockchain-macos-latest/*
